export const login = () => (dispatch) => {
  try {
  } catch (err) {
    console.log(err.message);
  }
};
